.\" Manpage for first bank of nerds program.
.\" Contact shadowing.bark@gmail.com, jviner2000@gmail.com, jm11palomares@gmail.com to correct errors or typos.

.\" Note: 'bank of nerds 1.0' tells the 'man' program this page belongs in section 1"

.TH BANK-OF-NERDS 1 "24 FEB 2023" "1.0" "Bank of Nerds man page"
.SH NAME
First Bank of Nerds \- A working model of a simple small bank.

.SH SYNOPSIS
.B bank_of_nerds 
\- [--option[=value]]

.SH DESCRIPTION
Bank of Nerds is a simple banking system that offers a modern and advanced set of features, including account management, customer management, and effortless transactions such as depositing and withdrawing. The interface is designed to be user-friendly and easy to use, allowing for seamless navigation without any confusion or inconvenience.

.SH OPTIONS
.B --<opt>=<value>
\- Prints out any and all information about the two required customers including any account information needed to access their accounts.

.SH BUGS
No known Bugs.

.SH AUTHOR
The programmers (shadowing.bark@gmail.com, jviner2000@gmail.com, jm11palomares@gmail.com).
